# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u6587\u4ef6\u540d')),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('src', models.CharField(max_length=255, verbose_name='\u6e90\u5730\u5740')),
                ('dest', models.CharField(max_length=255, verbose_name='\u76ee\u6807\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u6587\u4ef6\u7ba1\u7406',
                'verbose_name_plural': '\u6587\u4ef6\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='\u7ec4\u540d')),
                ('comment', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u5206\u7ec4\u7ba1\u7406',
                'verbose_name_plural': '\u5206\u7ec4\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.GenericIPAddressField(unique=True, verbose_name='\u4e3b\u673a\u5730\u5740')),
                ('user', models.CharField(default=None, max_length=10, verbose_name='\u64cd\u4f5c\u7528\u6237')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Group', to_field='name', verbose_name='\u7ec4\u540d')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u7ba1\u7406',
                'verbose_name_plural': '\u4e3b\u673a\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('\u65b0\u5efa\u6587\u4ef6', '\u65b0\u5efa\u6587\u4ef6'), ('\u65b0\u5efa\u76ee\u5f55', '\u65b0\u5efa\u76ee\u5f55'), ('\u5220\u9664\u6587\u4ef6/\u76ee\u5f55', '\u5220\u9664\u6587\u4ef6/\u76ee\u5f55'), ('\u8f6f\u8fde\u63a5', '\u8f6f\u8fde\u63a5'), ('\u786c\u94fe\u63a5', '\u786c\u94fe\u63a5')], max_length=64, unique=True, verbose_name='\u52a8\u4f5c')),
            ],
            options={
                'verbose_name': '\u52a8\u4f5c\u7ba1\u7406',
                'verbose_name_plural': '\u52a8\u4f5c\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Status', verbose_name='\u52a8\u4f5c'),
        ),
    ]
