# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='\u7ec4\u540d')),
                ('comment', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u5206\u7ec4\u7ba1\u7406',
                'verbose_name_plural': '\u5206\u7ec4\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.GenericIPAddressField(unique=True, verbose_name='\u4e3b\u673a\u5730\u5740')),
                ('auth_user', models.CharField(default='root', max_length=10, verbose_name='\u8ba4\u8bc1\u7528\u6237')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Group', to_field='name', verbose_name='\u7ec4\u540d')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u7ba1\u7406',
                'verbose_name_plural': '\u4e3b\u673a\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u4efb\u52a1\u63cf\u8ff0')),
                ('host', models.CharField(max_length=21485, verbose_name='\u4efb\u52a1\u4e3b\u673a')),
                ('result', models.TextField(verbose_name='\u6267\u884c\u7ed3\u679c')),
            ],
            options={
                'verbose_name': '\u4efb\u52a1\u7ba1\u7406',
                'verbose_name_plural': '\u4efb\u52a1\u7ba1\u7406',
            },
        ),
    ]
