# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='group',
            field=models.CharField(max_length=20, verbose_name='\u7ec4\u540d'),
        ),
    ]
