# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170524_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='status',
        ),
        migrations.AddField(
            model_name='host',
            name='auth_user',
            field=models.CharField(default='root', max_length=10, verbose_name='\u8ba4\u8bc1\u7528\u6237'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
