# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20170524_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.GenericIPAddressField(unique=True, verbose_name='\u4e3b\u673a\u5730\u5740')),
                ('auth_user', models.CharField(default='root', max_length=10, verbose_name='\u8ba4\u8bc1\u7528\u6237')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Group', to_field='name', verbose_name='\u7ec4\u540d')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u7ba1\u74061',
                'verbose_name_plural': '\u4e3b\u673a\u7ba1\u74061',
            },
        ),
    ]
