# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20170524_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Group', to_field='name', verbose_name='\u7ec4\u540d'),
        ),
    ]
