# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-17 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20170524_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u4efb\u52a1\u63cf\u8ff0')),
                ('host', models.CharField(max_length=21485, verbose_name='\u4efb\u52a1\u4e3b\u673a')),
                ('result', models.TextField(verbose_name='\u6267\u884c\u7ed3\u679c')),
            ],
            options={
                'verbose_name': '\u4efb\u52a1\u7ba1\u7406',
                'verbose_name_plural': '\u4efb\u52a1\u7ba1\u7406',
            },
        ),
    ]
