# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20170617_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.CharField(default='a', max_length=10, verbose_name='\u64cd\u4f5c\u7528\u6237'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='user',
            field=models.CharField(default='a', max_length=10, verbose_name='\u64cd\u4f5c\u7528\u6237'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.CharField(default='a', max_length=10, verbose_name='\u64cd\u4f5c\u7528\u6237'),
            preserve_default=False,
        ),
    ]
