# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20170618_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.CharField(max_length=20, verbose_name='\u64cd\u4f5c\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='host',
            name='user',
            field=models.CharField(max_length=20, verbose_name='\u64cd\u4f5c\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.CharField(max_length=20, verbose_name='\u64cd\u4f5c\u7528\u6237'),
        ),
    ]
