# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20170618_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u7ec4\u540d'),
        ),
    ]
