# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20170622_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='host',
        ),
        migrations.AddField(
            model_name='task',
            name='button_status',
            field=models.CharField(default='a', max_length=8, verbose_name='\u6309\u94ae\u72b6\u6001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.CharField(default='a', max_length=50, verbose_name='\u9879\u76ee\u6587\u4ef6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.CharField(default='a', max_length=50, verbose_name='\u4efb\u52a1\u7ec4\u522b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='run_status',
            field=models.CharField(default='info', max_length=50, verbose_name='\u4efb\u52a1\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(default='\u5f85\u90e8\u7f72', max_length=50, verbose_name='\u4efb\u52a1\u72b6\u6001'),
        ),
    ]
